#!/bin/sh

DATABASE_NAME="${DATABASE_NAME:-ripta}"
DATABASE_USER="${DATABASE_USER:-$USER}"
DATABASE_HOST="${DATABASE_HOST:-localhost}"

psql -h $DATABASE_HOST -U $DATABASE_USER -d $DATABASE_NAME -c "DROP TABLE IF EXISTS routes CASCADE"
psql -h $DATABASE_HOST -U $DATABASE_USER -d $DATABASE_NAME -c "DROP TABLE IF EXISTS stops CASCADE"
psql -h $DATABASE_HOST -U $DATABASE_USER -d $DATABASE_NAME -c "DROP TABLE IF EXISTS trips CASCADE"
psql -h $DATABASE_HOST -U $DATABASE_USER -d $DATABASE_NAME -c "DROP TABLE IF EXISTS stop_times CASCADE"
