// Code generated by protoc-gen-go.
// source: ripta.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	ripta.proto

It has these top-level messages:
	Location
	Stop
	Geocode
	GeocodeRequest
	GeocodeResponse
	ListStopsRequest
	StopLocationRequest
	StopsResponse
	RouteStopTime
	RouteStop
	RouteStopRequest
	RouteStopsResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Location struct {
	Lat  float64 `protobuf:"fixed64,1,opt,name=lat" json:"lat,omitempty"`
	Long float64 `protobuf:"fixed64,2,opt,name=long" json:"long,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Location) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

type Stop struct {
	Id       string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	StopId   string    `protobuf:"bytes,2,opt,name=stopId" json:"stopId,omitempty"`
	Name     string    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Location *Location `protobuf:"bytes,4,opt,name=location" json:"location,omitempty"`
	Routes   []string  `protobuf:"bytes,5,rep,name=routes" json:"routes,omitempty"`
}

func (m *Stop) Reset()                    { *m = Stop{} }
func (m *Stop) String() string            { return proto.CompactTextString(m) }
func (*Stop) ProtoMessage()               {}
func (*Stop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Stop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stop) GetStopId() string {
	if m != nil {
		return m.StopId
	}
	return ""
}

func (m *Stop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stop) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *Stop) GetRoutes() []string {
	if m != nil {
		return m.Routes
	}
	return nil
}

type Geocode struct {
	Address string  `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	Lat     float64 `protobuf:"fixed64,2,opt,name=lat" json:"lat,omitempty"`
	Long    float64 `protobuf:"fixed64,3,opt,name=long" json:"long,omitempty"`
}

func (m *Geocode) Reset()                    { *m = Geocode{} }
func (m *Geocode) String() string            { return proto.CompactTextString(m) }
func (*Geocode) ProtoMessage()               {}
func (*Geocode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Geocode) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Geocode) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Geocode) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

type GeocodeRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
}

func (m *GeocodeRequest) Reset()                    { *m = GeocodeRequest{} }
func (m *GeocodeRequest) String() string            { return proto.CompactTextString(m) }
func (*GeocodeRequest) ProtoMessage()               {}
func (*GeocodeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GeocodeRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type GeocodeResponse struct {
	Geocodes []*Geocode `protobuf:"bytes,1,rep,name=geocodes" json:"geocodes,omitempty"`
}

func (m *GeocodeResponse) Reset()                    { *m = GeocodeResponse{} }
func (m *GeocodeResponse) String() string            { return proto.CompactTextString(m) }
func (*GeocodeResponse) ProtoMessage()               {}
func (*GeocodeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GeocodeResponse) GetGeocodes() []*Geocode {
	if m != nil {
		return m.Geocodes
	}
	return nil
}

type ListStopsRequest struct {
}

func (m *ListStopsRequest) Reset()                    { *m = ListStopsRequest{} }
func (m *ListStopsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListStopsRequest) ProtoMessage()               {}
func (*ListStopsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type StopLocationRequest struct {
	Route string  `protobuf:"bytes,1,opt,name=route" json:"route,omitempty"`
	Lat   float64 `protobuf:"fixed64,2,opt,name=lat" json:"lat,omitempty"`
	Long  float64 `protobuf:"fixed64,3,opt,name=long" json:"long,omitempty"`
}

func (m *StopLocationRequest) Reset()                    { *m = StopLocationRequest{} }
func (m *StopLocationRequest) String() string            { return proto.CompactTextString(m) }
func (*StopLocationRequest) ProtoMessage()               {}
func (*StopLocationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StopLocationRequest) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *StopLocationRequest) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *StopLocationRequest) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

type StopsResponse struct {
	Stop []*Stop `protobuf:"bytes,1,rep,name=stop" json:"stop,omitempty"`
}

func (m *StopsResponse) Reset()                    { *m = StopsResponse{} }
func (m *StopsResponse) String() string            { return proto.CompactTextString(m) }
func (*StopsResponse) ProtoMessage()               {}
func (*StopsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StopsResponse) GetStop() []*Stop {
	if m != nil {
		return m.Stop
	}
	return nil
}

type RouteStopTime struct {
	ScheduleTime string `protobuf:"bytes,1,opt,name=scheduleTime" json:"scheduleTime,omitempty"`
	ArrivalTime  string `protobuf:"bytes,2,opt,name=arrivalTime" json:"arrivalTime,omitempty"`
}

func (m *RouteStopTime) Reset()                    { *m = RouteStopTime{} }
func (m *RouteStopTime) String() string            { return proto.CompactTextString(m) }
func (*RouteStopTime) ProtoMessage()               {}
func (*RouteStopTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RouteStopTime) GetScheduleTime() string {
	if m != nil {
		return m.ScheduleTime
	}
	return ""
}

func (m *RouteStopTime) GetArrivalTime() string {
	if m != nil {
		return m.ArrivalTime
	}
	return ""
}

type RouteStop struct {
	StopId string         `protobuf:"bytes,1,opt,name=stopId" json:"stopId,omitempty"`
	Time   *RouteStopTime `protobuf:"bytes,2,opt,name=time" json:"time,omitempty"`
}

func (m *RouteStop) Reset()                    { *m = RouteStop{} }
func (m *RouteStop) String() string            { return proto.CompactTextString(m) }
func (*RouteStop) ProtoMessage()               {}
func (*RouteStop) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *RouteStop) GetStopId() string {
	if m != nil {
		return m.StopId
	}
	return ""
}

func (m *RouteStop) GetTime() *RouteStopTime {
	if m != nil {
		return m.Time
	}
	return nil
}

type RouteStopRequest struct {
	RouteId string `protobuf:"bytes,1,opt,name=routeId" json:"routeId,omitempty"`
	StopId  string `protobuf:"bytes,2,opt,name=stopId" json:"stopId,omitempty"`
}

func (m *RouteStopRequest) Reset()                    { *m = RouteStopRequest{} }
func (m *RouteStopRequest) String() string            { return proto.CompactTextString(m) }
func (*RouteStopRequest) ProtoMessage()               {}
func (*RouteStopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *RouteStopRequest) GetRouteId() string {
	if m != nil {
		return m.RouteId
	}
	return ""
}

func (m *RouteStopRequest) GetStopId() string {
	if m != nil {
		return m.StopId
	}
	return ""
}

type RouteStopsResponse struct {
	Stop []*RouteStop `protobuf:"bytes,1,rep,name=stop" json:"stop,omitempty"`
}

func (m *RouteStopsResponse) Reset()                    { *m = RouteStopsResponse{} }
func (m *RouteStopsResponse) String() string            { return proto.CompactTextString(m) }
func (*RouteStopsResponse) ProtoMessage()               {}
func (*RouteStopsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *RouteStopsResponse) GetStop() []*RouteStop {
	if m != nil {
		return m.Stop
	}
	return nil
}

func init() {
	proto.RegisterType((*Location)(nil), "pb.Location")
	proto.RegisterType((*Stop)(nil), "pb.Stop")
	proto.RegisterType((*Geocode)(nil), "pb.Geocode")
	proto.RegisterType((*GeocodeRequest)(nil), "pb.GeocodeRequest")
	proto.RegisterType((*GeocodeResponse)(nil), "pb.GeocodeResponse")
	proto.RegisterType((*ListStopsRequest)(nil), "pb.ListStopsRequest")
	proto.RegisterType((*StopLocationRequest)(nil), "pb.StopLocationRequest")
	proto.RegisterType((*StopsResponse)(nil), "pb.StopsResponse")
	proto.RegisterType((*RouteStopTime)(nil), "pb.RouteStopTime")
	proto.RegisterType((*RouteStop)(nil), "pb.RouteStop")
	proto.RegisterType((*RouteStopRequest)(nil), "pb.RouteStopRequest")
	proto.RegisterType((*RouteStopsResponse)(nil), "pb.RouteStopsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ripta service

type RiptaClient interface {
	Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error)
	ListStops(ctx context.Context, in *ListStopsRequest, opts ...grpc.CallOption) (*StopsResponse, error)
	GetStopsByLocation(ctx context.Context, in *StopLocationRequest, opts ...grpc.CallOption) (*StopsResponse, error)
	RouteStopsByStopID(ctx context.Context, in *RouteStopRequest, opts ...grpc.CallOption) (*RouteStopsResponse, error)
}

type riptaClient struct {
	cc *grpc.ClientConn
}

func NewRiptaClient(cc *grpc.ClientConn) RiptaClient {
	return &riptaClient{cc}
}

func (c *riptaClient) Geocode(ctx context.Context, in *GeocodeRequest, opts ...grpc.CallOption) (*GeocodeResponse, error) {
	out := new(GeocodeResponse)
	err := grpc.Invoke(ctx, "/pb.Ripta/Geocode", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riptaClient) ListStops(ctx context.Context, in *ListStopsRequest, opts ...grpc.CallOption) (*StopsResponse, error) {
	out := new(StopsResponse)
	err := grpc.Invoke(ctx, "/pb.Ripta/ListStops", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riptaClient) GetStopsByLocation(ctx context.Context, in *StopLocationRequest, opts ...grpc.CallOption) (*StopsResponse, error) {
	out := new(StopsResponse)
	err := grpc.Invoke(ctx, "/pb.Ripta/GetStopsByLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riptaClient) RouteStopsByStopID(ctx context.Context, in *RouteStopRequest, opts ...grpc.CallOption) (*RouteStopsResponse, error) {
	out := new(RouteStopsResponse)
	err := grpc.Invoke(ctx, "/pb.Ripta/RouteStopsByStopID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ripta service

type RiptaServer interface {
	Geocode(context.Context, *GeocodeRequest) (*GeocodeResponse, error)
	ListStops(context.Context, *ListStopsRequest) (*StopsResponse, error)
	GetStopsByLocation(context.Context, *StopLocationRequest) (*StopsResponse, error)
	RouteStopsByStopID(context.Context, *RouteStopRequest) (*RouteStopsResponse, error)
}

func RegisterRiptaServer(s *grpc.Server, srv RiptaServer) {
	s.RegisterService(&_Ripta_serviceDesc, srv)
}

func _Ripta_Geocode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeocodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiptaServer).Geocode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ripta/Geocode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiptaServer).Geocode(ctx, req.(*GeocodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ripta_ListStops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiptaServer).ListStops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ripta/ListStops",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiptaServer).ListStops(ctx, req.(*ListStopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ripta_GetStopsByLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiptaServer).GetStopsByLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ripta/GetStopsByLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiptaServer).GetStopsByLocation(ctx, req.(*StopLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ripta_RouteStopsByStopID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteStopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiptaServer).RouteStopsByStopID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Ripta/RouteStopsByStopID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiptaServer).RouteStopsByStopID(ctx, req.(*RouteStopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ripta_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Ripta",
	HandlerType: (*RiptaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Geocode",
			Handler:    _Ripta_Geocode_Handler,
		},
		{
			MethodName: "ListStops",
			Handler:    _Ripta_ListStops_Handler,
		},
		{
			MethodName: "GetStopsByLocation",
			Handler:    _Ripta_GetStopsByLocation_Handler,
		},
		{
			MethodName: "RouteStopsByStopID",
			Handler:    _Ripta_RouteStopsByStopID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ripta.proto",
}

func init() { proto.RegisterFile("ripta.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x1f, 0x69, 0x92, 0x71, 0x53, 0xd2, 0x69, 0x55, 0xac, 0x88, 0x43, 0x58, 0x09, 0xc8,
	0x85, 0x08, 0x05, 0x04, 0x12, 0xc7, 0x28, 0x52, 0x15, 0xd4, 0x0b, 0x0b, 0xfc, 0x00, 0x27, 0x5e,
	0x15, 0x4b, 0x6e, 0xd6, 0xf1, 0xae, 0x91, 0x72, 0xe7, 0x7f, 0x83, 0xf6, 0x33, 0x76, 0x00, 0xa9,
	0xa7, 0xec, 0xbc, 0x1d, 0xbf, 0x79, 0x6f, 0x66, 0x36, 0x90, 0xd4, 0x45, 0x25, 0xb3, 0x79, 0x55,
	0x73, 0xc9, 0x31, 0xac, 0x36, 0xe4, 0x2d, 0x0c, 0xee, 0xf8, 0x36, 0x93, 0x05, 0xdf, 0xe1, 0x18,
	0xa2, 0x32, 0x93, 0x69, 0x30, 0x0d, 0x66, 0x01, 0x55, 0x47, 0x44, 0x88, 0x4b, 0xbe, 0xbb, 0x4f,
	0x43, 0x0d, 0xe9, 0x33, 0xf9, 0x15, 0x40, 0xfc, 0x55, 0xf2, 0x0a, 0x2f, 0x20, 0x2c, 0x72, 0x9d,
	0x3d, 0xa4, 0x61, 0x91, 0xe3, 0x0d, 0x9c, 0x09, 0xc9, 0xab, 0x75, 0xae, 0xd3, 0x87, 0xd4, 0x46,
	0x8a, 0x64, 0x97, 0x3d, 0xb0, 0x34, 0xd2, 0xa8, 0x3e, 0xe3, 0x0c, 0x06, 0xa5, 0x2d, 0x9b, 0xc6,
	0xd3, 0x60, 0x96, 0x2c, 0xce, 0xe7, 0xd5, 0x66, 0xee, 0xa4, 0x50, 0x7f, 0xab, 0x58, 0x6b, 0xde,
	0x48, 0x26, 0xd2, 0xde, 0x34, 0x52, 0xac, 0x26, 0x22, 0x6b, 0xe8, 0xdf, 0x32, 0xbe, 0xe5, 0x39,
	0xc3, 0x14, 0xfa, 0x59, 0x9e, 0xd7, 0x4c, 0x08, 0xab, 0xc6, 0x85, 0xce, 0x51, 0xf8, 0xb7, 0xa3,
	0xa8, 0xe5, 0xe8, 0x15, 0x5c, 0x58, 0x2a, 0xca, 0xf6, 0x0d, 0x13, 0x12, 0xaf, 0xa1, 0xb7, 0x6f,
	0x58, 0x7d, 0xb0, 0x7c, 0x26, 0x20, 0x9f, 0xe0, 0xa9, 0xcf, 0x13, 0x15, 0xdf, 0x09, 0x86, 0xaf,
	0x61, 0x70, 0x6f, 0x20, 0x55, 0x3b, 0x9a, 0x25, 0x8b, 0x44, 0xf9, 0x70, 0x69, 0xfe, 0x92, 0x20,
	0x8c, 0xef, 0x0a, 0x21, 0x55, 0xe3, 0x84, 0xad, 0x42, 0xbe, 0xc0, 0x95, 0x8a, 0xbd, 0xe9, 0x63,
	0x71, 0xed, 0xd1, 0x15, 0xd7, 0xc1, 0x23, 0xad, 0xbc, 0x81, 0x91, 0x2d, 0x61, 0x05, 0x3e, 0x87,
	0x58, 0x8d, 0xc1, 0x8a, 0x1b, 0x28, 0x71, 0x2a, 0x81, 0x6a, 0x94, 0x7c, 0x87, 0x11, 0x55, 0xec,
	0x0a, 0xfa, 0x56, 0x3c, 0x30, 0x24, 0x70, 0x2e, 0xb6, 0x3f, 0x58, 0xde, 0x94, 0x4c, 0xc5, 0x56,
	0x42, 0x07, 0xc3, 0x29, 0x24, 0x59, 0x5d, 0x17, 0x3f, 0xb3, 0x52, 0xa7, 0x98, 0x61, 0xb7, 0x21,
	0xf2, 0x19, 0x86, 0x9e, 0xb6, 0xb5, 0x16, 0x41, 0x67, 0x2d, 0x5e, 0x42, 0x2c, 0xdd, 0xf7, 0xc9,
	0xe2, 0x52, 0x29, 0xeb, 0x68, 0xa1, 0xfa, 0x9a, 0xac, 0x60, 0xec, 0x61, 0xd7, 0xa1, 0x14, 0xfa,
	0xba, 0x29, 0x9e, 0xd3, 0x85, 0xff, 0xdb, 0x41, 0xf2, 0x11, 0xd0, 0xb3, 0x1c, 0x9b, 0xf3, 0xa2,
	0xd3, 0x9c, 0x51, 0x47, 0x82, 0xe9, 0xd0, 0xe2, 0x77, 0x00, 0x3d, 0xaa, 0xde, 0x0c, 0xbe, 0x3f,
	0x2e, 0x1c, 0xb6, 0x67, 0x6c, 0x34, 0x4d, 0xae, 0x3a, 0x98, 0x29, 0x40, 0x9e, 0xe0, 0x07, 0x18,
	0xfa, 0xb9, 0xe3, 0xb5, 0xde, 0xf1, 0x93, 0x35, 0x98, 0x5c, 0xba, 0xa1, 0x88, 0xd6, 0x77, 0x4b,
	0xc0, 0x5b, 0x66, 0xf2, 0x96, 0x07, 0xff, 0x42, 0x9f, 0xb9, 0xd4, 0x93, 0x9d, 0xf9, 0x37, 0xc7,
	0xaa, 0x6d, 0x7a, 0x79, 0x50, 0x3f, 0xeb, 0x95, 0x11, 0x71, 0xda, 0xd2, 0xc9, 0x4d, 0x07, 0x6d,
	0xb1, 0x6c, 0xce, 0xf4, 0x9f, 0xc5, 0xbb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x53, 0xbf,
	0xfb, 0x3b, 0x04, 0x00, 0x00,
}
